### ISSUE TITLE
Missing A.circled, a.circled, Aturned required by the GF Pan African encoding

### ISSUE THREAD

**Issue by EbenSorkin** [clauseggers/Playfair#60]
Playfair is still missing 3 glyphs that were added fairly late in the GF Pan African encoding update process: A.circled, a.circled, Aturned. Unicode: 24B6, 24D0, 2C6F

**Comment by clauseggers** [comment]
Do you have reference renderings of the first two, a Unicode proposal or such?

**Comment by EbenSorkin** [comment]
John Hudson's Brill has some <img width="443" alt="image" src="https://github.com/user-attachments/assets/934abf3d-d107-4d0f-8074-be38093c2fc6">
<img width="426" alt="image" src="https://github.com/user-attachments/assets/15625bd5-adeb-42d3-a389-9219a52ba28c">
<img width="362" alt="image" src="https://github.com/user-attachments/assets/1d2b989b-0bc3-490e-9fdc-795b2b6864dc">

**Comment by clauseggers** [comment]
The Brill face is not a good reference. It contains many morphologies/renderings that are not accepted in SSA. I don’t know if he didn’t know better at the time or if Brill wanted them that way for some other use in academia.

So do you have a useful reference? Anything in context?

**Comment by EbenSorkin** [comment]
I have asked Denis for these. Let's see what he says.

**Comment by moyogo** [comment]
Ⓐ 24B6, ⓐ 24D0 and Ɐ 2C6F, ɐ 0250 are used in different orthographies of [Koalib](https://en.wikipedia.org/wiki/Koalib_language), the first two in the SIL orthography and the last two in the orthography used by Nicolas Quint and some Koalib diaspor authors.

In the SIL orthography @ 0040 was used, and instead of adding a capital character Unicode recommends using Ⓐ 24B6 and ⓐ 24D0.

Ⓐ 24B6, ⓐ 24D0 were initially encoded for bullet indeces and may have large circles around normal sized letters or slightly smaller. The shapes in Brill are normal.

For use in Koalib, the exceptation would be that they have the circle not too large, but larger than letter-size, with a smaller letter in it. for the lowercase with an open circle starting at the script form of a like @. Similarly the uppercase open circle could start at the bottom right of the capital letter.
There isn’t much evidence for the use besides SIL fonts and a couple of samples in https://www.unicode.org/review/pr-40-atsigns.pdf (or Unicode related documents):
<img width="472" alt="Screenshot 2024-09-18 at 19 39 33" src="https://github.com/user-attachments/assets/bf24d77c-4837-4481-a252-eba894243029">
<img width="346" alt="Screenshot 2024-09-18 at 19 39 51" src="https://github.com/user-attachments/assets/b67b32cf-bef7-453c-9c62-ffefa5b2995b">

In handwriting the lowercase can have simplified forms like @ from https://youtu.be/D0k64Au7c8o?si=nC28bO1OulLgJ8bL&t=993 :
<img width="122" alt="Screenshot 2024-09-18 at 19 31 12" src="https://github.com/user-attachments/assets/3d24bdc7-1251-414b-bce5-70d8c476cef5">

Generally speaking the use of Ⓐ 24B6, ⓐ 24D0 feels like a hack, and SIL fonts don’t seem to support it.

Ɐ 2C6F, ɐ 0250 should be straight forward although ɐ 0250 vs. ɒ 0252 have the same issues as a 0061 vs. ɑ 0251 in italic. In the case of ɐ 0250 it would be useful to have the default as a turned slanted a instead of a turned script a. A slanted a would be useful as an alternate glyph for a 0061 as well.

**Comment by moyogo** [comment]
Just so its clear, there is no [https://learn.microsoft.com/en-us/typography/opentype/spec/languagetags](OpenType language system tag) for Koalib so a `locl` feature substitution cannot be properly coded in fonts.

The minimum is to have Ⓐ 24B6, ⓐ 24D0 with normal shapes, bullet index shapes, so text can be displayed without font fallback or notdef glyphs.
Having Koalib capital and lowercase at-forms as glyph alternates with some feature (cvXX or ssXX, and aalt) for Koalib can be useful.

**Comment by EbenSorkin** [comment]
When you say ss or alt firms are you suggesting they always be made to
address cultural variation or because fonts sometimes have style variations
and these should be reflected not just in a and A but in these letters?
24b6 for example.

**Comment by clauseggers** [comment]
So in essence the two circled glyphs we want for Koalib are not encoded in Unicode. I will not be designing and adding random circled letters. If you want Koalib glyphs included then the move is to either wait until they are assigned a Unicode codepoint, or place them in PUA for the time being.

I shall be happy to place them in PUA for now, but highjacking the circled letters will not be happening.

**Comment by moyogo** [comment]
> When you say ss or alt firms are you suggesting they always be made to
address cultural variation or because fonts sometimes have style variations
and these should be reflected not just in a and A but in these letters?
24b6 for example.

@EbenSorkin I’m not sure I understand.

> So in essence the two circled glyphs we want for Koalib are not encoded in Unicode. I will not be designing and adding random circled letters. If you want Koalib glyphs included then the move is to either wait until they are assigned a Unicode codepoint, or place them in PUA for the time being.

@clauseggers Unicode recommends using Ⓐ 24B6, ⓐ 24D0, or at least it won’t change @ or add characters that may create issues with @.

An example of ⓐ in use is the Heiban language orthography used in the 1966 Bible translation at https://biblesociety-sudan.org/bible/HBN/MAT.1/ or https://www.bible.com/bible/3402/MAT.1.HBN

The minimum is probably to have Ⓐ 24B6, ⓐ 24D0 with normal glyphs.
Having Koalib specific glyphs as alternates may be nice but realistically they may be difficult to access for normal users.

**Comment by EbenSorkin** [comment]
I see I mistyped. I said "ss or alt firms" but I meant "ss or alt forms" or
versions.

So if you did want to add support for Koalib you would create a variation
and use the @ like ring rather than a full ring as al alt but there is no
localization code available at this time. I see.

Because SIL have listed the version with the @ style ring as depreciated (
according to Wikipedia... ) that would seem to argue for using the plain
ring - no?

-e.

**Comment by moyogo** [comment]
> Because SIL have listed the version with the @ style ring as depreciated (
according to Wikipedia... ) that would seem to argue for using the plain
ring - no?

@EbenSorkin Yes, if that form is deprecated it’s easier for everybody.
@clauseggers I think you’re earlier assessment may be the best actually: these letter forms aren’t really encoded in Unicode and using Ⓐ, ⓐ is a hack, or at least it feels like it.

There’s a proposal for a [curl](https://www.unicode.org/L2/L2023/23137-n5227-combining-overcurl.pdf) that could be another alternative to represent these letters but it’s not clear when or how this would added.

**Comment by EbenSorkin** [comment]
Dave,

As I understand it the letters in question are part of the current
requirements for full support but perhaps were not at the time that Claus
made his agreement so does that mean he isn't obligated to make them at
this time?

-e.

**Comment by EbenSorkin** [comment]
What does not encodes properly mean, claus?

**Comment by EbenSorkin** [comment]
By encoded do you mean that their shapes or the characteristics of the
shapes become more stable?

**Comment by clauseggers** [comment]
Eben this matter has been closed for now. You asked questions that were discussed earlier in this thread.
